-- Add new invoice fields
ALTER TABLE invoices
ADD COLUMN IF NOT EXISTS fruit_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS fruit_price DECIMAL(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS central_kitchen_cost DECIMAL(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS in_unit_overhead DECIMAL(10,2) DEFAULT 0.00;
